language: ruby
sudo: false

cache: bundler

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master

before_install:
  - source $HOME/otp/19.3/activate
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
  - gem install bundler
