os: Visual Studio 2017
platform:
  - x64

skip_tags: true
branches:
  only:
    - master

cache:
  - bundle

environment:
  matrix:
    - ruby_version: "25-x64"

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - bundle install || bundle install || bundle install

build: off

before_test:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle env

test_script:
  - bundle exec rake
