os: Windows Server 2012 R2
platform:
  - x64

skip_tags: true
branches:
  only:
    - master

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rake spec
