os: Windows Server 2012 R2
platform:
  - x64

skip_tags: true
branches:
  only:
    - master

install:
  - set PATH=C:\Ruby22\bin;%PATH%

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rake spec
