---
project:
  alias: license_scout

slack:
  notify_channel: releng-notify

github:
  version_tag_format: "v{{version}}"
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  release_branch:
    - master:
        version_constraint: 2.*
    - 1-stable:
        version_constraint: 1.*

habitat_packages:
  - license_scout

rubygems:
  - license_scout

pipelines:
  - verify:
      organization: chef-oss

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_version.sh:
      only_if:
        - built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version
  - built_in:trigger_habitat_package_build:
      ignore_labels:
        - "Expeditor: Skip Habitat"
      only_if:
        - built_in:bump_version

promote:
  actions:
    - built_in:rollover_changelog
    - built_in:publish_rubygems
    - built_in:promote_habitat_packages
